# Bitbucket Pipelines YAML file for building Android Application
# Reference Links:
# - Bitbucket Pipelines Documentation: https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
# - Caching Dependencies: https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
# - Using Artifacts: https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
# - Docker Image Details: https://hub.docker.com/r/androidsdk/android-31

image: androidsdk/android-31

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build Debug .aab
          caches:
            - gradle  # Gradle cache to speed up build
            - android-34  # Android SDK 34 cache
          script:
            # Check if SDK 34 is already cached, if not then install it
            - if [ ! -d "$HOME/android-34" ]; then yes | sdkmanager "platforms;android-33"; fi
            # Copy the installed SDK 34 to cacheable directory
            - cp -r "$ANDROID_HOME/platforms/android-34" "$HOME/android-34" || true
            - echo "$SIGNING_JKS_FILE" | base64 --decode > app/signing.jks
            # Run the build task for Debug .aab
            - ./gradlew bundleDebug
          artifacts:
            - app/build/outputs/**

  branches:
    'release/*':
      - parallel:
          - step:
              name: Run lint for Release
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step:
              name: Build Release .aab and
              caches:
                - gradle
              script:
                - echo "$SIGNING_JKS_FILE" | base64 --decode > app/signing.jks
                - ./gradlew bundleRelease
              artifacts:
                - app/build/outputs/**
      - step:
          name: Publish Internal
          image: bitbucketpipelines/android-ci-image
          deployment: Internal
          script:
            - echo $GOOGLE_API_KEY_JSON > google_play_api_key.json
            - echo "$SIGNING_JKS_FILE" | base64 -d > android-signing-keystore.jks
            - ./gradlew publishReleaseApk




    'develop':
      - parallel:
          - step:
              name: Run lint for Develop
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step:
              name: Build Release .aab for Develop
              caches:
                - gradle
              script:
                - ./gradlew bundleRelease
              artifacts:
                - app/build/outputs/**
          - step:
              name: Build Debug .aab for Develop
              caches:
                - gradle
              script:
                - ./gradlew bundleDebug
              artifacts:
                - app/build/outputs/**

# Definitions for custom cache directories
definitions:
  caches:
    android-34: $HOME/android-34  # Cache directory for Android SDK 34