# Bitbucket Pipelines Template to build, test your Android Application.

# This template contains 3 parallel steps to build Android application, run Android code scanning tool and run unit tests.
# For more details see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/

# Docker for Android SDK 30 with pre-installed build tools and emulator image.
# Note: This docker image is created and maintained by a non official third party. For more details see: https://hub.docker.com/r/androidsdk/android-30
image: androidsdk/android-31

pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step: # step to build Android debug application
          name: Pull request build
          caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
            - gradle
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/

  branches:
    '**':
      - parallel:
          - step: # step to build Android debug application
              name: Debug Unit tests
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew testDebugUnitTest
              artifacts:
                - app/build/outputs/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
          - step:
              name: Lint
              caches:
                - gradle
              script:
                - ./gradlew lint
    'feature/*':
      - parallel:
          - step: # step to build Android debug application
              name: Debug Unit tests
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew testDebugUnitTest

          - step:
              name: Debug lint
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
    'release/*': # step to build Release branches
      - parallel:
          - step:
              name: Release unit tests
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew testReleaseUnitTest
          - step:
              name: Release lint
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                    - app/build/reports/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
          - step: # step to build Android release application
              name: Android Release Application
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew assembleRelease
              artifacts:
                - app/build/outputs/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
    'develop':
      - parallel:
          - step:
              name: Release unit tests
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew testReleaseUnitTest
          - step:
              name: Release lint
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
          - step: # step to build Android release application
              name: Android Release Application
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew assembleRelease
              artifacts:
                - app/build/outputs/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
          - step: # step to build Android debug application
              name: Android Debug Application
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew assembleDebug
              artifacts:
                - app/build/outputs/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
