# Bitbucket Pipelines YAML file for building Android Application
# Reference Links:
# - Bitbucket Pipelines Documentation: https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
# - Caching Dependencies: https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
# - Using Artifacts: https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
# - Docker Image Details: https://hub.docker.com/r/androidsdk/android-31

image: androidsdk/android-31

pipelines:
  pull-requests:
    '**':
      - step:
          name: Create keystore
          script:
            - mkdir keys
            - echo $KEYSTORE_FILE_BASE64 | base64 --decode > keys/$KEYSTORE_FILE
          artifacts:
            - keys/**
      - step:
          name: Build Debug .aab
          caches:
            - gradle  # Gradle cache to speed up build
            - android-34  # Android SDK 34 cache
          script:
            # Check if SDK 34 is already cached, if not then install it
            - if [ ! -d "$HOME/android-34" ]; then yes | sdkmanager "platforms;android-33"; fi
            # Copy the installed SDK 34 to cacheable directory
            - cp -r "$ANDROID_HOME/platforms/android-34" "$HOME/android-34" || true
            # Run the build task for Debug .aab
            - ./gradlew -PKEYSTORE_FILE= keys/$KEYSTORE_FILE 
                        -PKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
                        -PKEY_ALIAS=$KEY_ALIAS
                        -PKEY_PASSWORD=$KEY_PASSWORD
                        bundleDebug
          artifacts:
            - app/build/outputs/**

  branches:
    'release/*':
      - step:
          name: Create keystore
          script:
            - mkdir keys
            - echo $KEYSTORE_FILE_BASE64 | base64 --decode > keys/$KEYSTORE_FILE
          artifacts:
            - keys/**
      - parallel:
          - step:
              name: Run lint for Release
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step:
              name: Build Release .aab
              caches:
                - gradle
              script:
                # Check if SDK 34 is already cached, if not then install it
                - if [ ! -d "$HOME/android-34" ]; then yes | sdkmanager "platforms;android-33"; fi
                # Copy the installed SDK 34 to cacheable directory
                - cp -r "$ANDROID_HOME/platforms/android-34" "$HOME/android-34" || true
                - ./gradlew -PKEYSTORE_FILE= keys/$KEYSTORE_FILE
                  -PKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
                  -PKEY_ALIAS=$KEY_ALIAS
                  -PKEY_PASSWORD=$KEY_PASSWORD
                  -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                  bundleRelease
              artifacts:
                - app/build/outputs/**




    'develop':
      - parallel:
          - step:
              name: Run lint for Develop
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step:
              name: Build Release .aab for Develop
              caches:
                - gradle
              script:
                - ./gradlew bundleRelease
              artifacts:
                - app/build/outputs/**
          - step:
              name: Build Debug .aab for Develop
              caches:
                - gradle
              script:
                - ./gradlew bundleDebug
              artifacts:
                - app/build/outputs/**

# Definitions for custom cache directories
definitions:
  caches:
    android-34: $HOME/android-34  # Cache directory for Android SDK 34