# Bitbucket Pipelines YAML file for building Android Application
# Reference Links:
# - Bitbucket Pipelines Documentation: https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
# - Caching Dependencies: https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
# - Using Artifacts: https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
# - Docker Image Details: https://hub.docker.com/r/androidsdk/android-31

image: androidsdk/android-31

pipelines:
  #will run for all PRs
  pull-requests:
    '**':
      - step: &id0031
          name: Build Debug .apk
          caches:
            - gradle  # Gradle cache to speed up build
            - android-34  # Android SDK 34 cache
          script:
            # Check if SDK 34 is already cached, if not then install it
            - if [ ! -d "$HOME/android-34" ]; then yes | sdkmanager "platforms;android-33"; fi
            # Copy the installed SDK 34 to cacheable directory
            - cp -r "$ANDROID_HOME/platforms/android-34" "$HOME/android-34" || true
            # Run the build task for Debug .apk, which is not signed
            - "./gradlew -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                        assembleDebug "
            #We are building an apk here instead of the bundle as it makes it easier to install manually
          artifacts:
            - app/build/outputs/**

  branches:
    #will run for release/ branches
    'release/*':
      - step: &id0010
          name: Create keystore & API Key
          script:
            - mkdir keys
            - echo $KEYSTORE_FILE_BASE64 | base64 --decode > keys/$KEYSTORE_FILE
            - echo $GOOGLE_PLAY_API_KEY_BASE64 | base64 --decode > keys/$GOOGLE_PLAY_API_KEY
          artifacts:
            - keys/**
      - parallel:
          - step: &id0021
              name: Run lint for Release
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step: &id0022
              name: Build Release .aab
              caches:
                - gradle
                - android-34
              script:
                # Check if SDK 34 is already cached, if not then install it
                - if [ ! -d "$HOME/android-34" ]; then yes | sdkmanager "platforms;android-33"; fi
                # Copy the installed SDK 34 to cacheable directory
                - cp -r "$ANDROID_HOME/platforms/android-34" "$HOME/android-34" || true
                - ./gradlew -PKEYSTORE_FILE=../keys/$KEYSTORE_FILE
                  -PKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
                  -PKEY_ALIAS=$KEY_ALIAS
                  -PKEY_PASSWORD=$KEY_PASSWORD
                  -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                  -PGOOGLE_PLAY_API_KEY=../keys/$GOOGLE_PLAY_API_KEY
                  -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                  publishBundle --info
              artifacts:
                - app/build/outputs/**

    'develop':
      - step: *id0010
      - parallel:
          - step: *id0021
          - step: *id0022

# Definitions for custom cache directories
definitions:
  caches:
    android-34: $HOME/android-34  # Cache directory for Android SDK 34